mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          bucket_name: "mimir-bucket"
          endpoint: "http://new-minio.new-lgtm.svc.cluster.local:9000"
          access_key_id: "tq5CBo9EEcld6752NwSd" # This is a secret injected via an environment variable
          secret_access_key: "HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9" # This is a secret injected via an environment variable
          http:
            insecure_skip_verify: true

minio:
  enabled: false

global:
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
