mimir:
  structuredConfig: |
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: tq5CBo9EEcld6752NwSd
        bucket_name: mimir-ruler
        endpoint: new-minio.new-lgtm.svc.cluster.local:9000
        http:
          insecure_skip_verify: true
        insecure: false
        secret_access_key: HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      s3:
        access_key_id: tq5CBo9EEcld6752NwSd
        bucket_name: mimir-tsdb
        endpoint: new-minio.new-lgtm.svc.cluster.local:9000
        http:
          insecure_skip_verify: true
        insecure: false
        secret_access_key: HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
    compactor:
      compaction_interval: 30m
      data_dir: /data
      deletion_delay: 2h
      first_level_compaction_wait_period: 25m
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      sharding_ring:
        heartbeat_period: 1m
        heartbeat_timeout: 4m
        wait_stability_min_duration: 1m
      symbols_flushers_concurrency: 4
    distributor:
      ring:
        heartbeat_period: 1m
        heartbeat_timeout: 4m
        instance_addr: ${POD_ID}

    ingester:
      ring:
        final_sleep: 0s
        heartbeat_period: 2m
        heartbeat_timeout: 10m
        instance_addr: ${POD_IP}
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        zone_awareness_enabled: true
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      max_cache_freshness: 10m
      max_query_parallelism: 240
      max_total_query_length: 12000h
    memberlist:
      abort_if_cluster_join_fails: false
      bind_addr:
      - ${MY_POD_IP}
      compression_enabled: false
      join_members:
      - mimir-gossip-ring:7946
      - dns+mimir-gossip-ring.serengeti-mimir-prom.svc.cluster.local.:7946
    querier:
      max_concurrent: 16
    query_scheduler:
      max_outstanding_requests_per_tenant: 800

    runtime_config:
      file: /var/mimir/runtime.yaml
    store_gateway:
      sharding_ring:
        heartbeat_period: 1m
        heartbeat_timeout: 4m
        kvstore:
          prefix: multi-zone/
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        wait_stability_min_duration: 1m
        zone_awareness_enabled: true
    usage_stats:
      installation_mode: helm