mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: http://new-minio.new-lgtm.svc.cluster.local:9000
          region: zzman
          secret_access_key: "HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9" # This is a secret injected via an environment variable
          access_key_id: "tq5CBo9EEcld6752NwSd" # This is a secret injected via an environment variable

    blocks_storage:
      s3:
        bucket_name: mimir-blocks

    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager

    ruler_storage:
      s3:
        bucket_name: mimir-ruler

minio:
  enabled: false

global:
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
