  loki:
    memberlist:
      joinMembers:
        - loki-memberlist

    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    ingester:
      chunk_encoding: snappy

    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4

    pattern_ingester:
      enabled: true

    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
      max_query_length: 8760h    # 1년
      max_query_range: 8760h

    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        s3: null
        endpoint: http://new-minio.new-lgtm.svc.cluster.local:9000
        region: dummy
        secretAccessKey: HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9
        accessKeyId: tq5CBo9EEcld6752NwSd
        s3ForcePathStyle: true
        insecure: true

  deploymentMode: SimpleScalable

  backend:
    replicas: 2
  read:
    replicas: 2
  write:
    replicas: 3 # To ensure data durability with replication

  minio:
    enabled: false

  gateway:
    service:
      type: LoadBalancer

  chunksCache:
    allocatedMemory: 1024