apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
