apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      # Init Container: OTEL Java Agent 다운로드
      initContainers:
      - name: download-otel-agent
        image: curlimages/curl:7.88.1
        command: ["sh", "-c"]
        args:
          - curl -L -o /otel/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.30.0/opentelemetry-javaagent.jar
        volumeMounts:
        - name: otel-agent
          mountPath: /otel

      containers:
      - name: tomcat
        image: tomcat:10-jdk17
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.new-lgtm.svc.cluster.local:12345"
        - name: OTEL_SERVICE_NAME
          value: "tomcat-app"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/otel/opentelemetry-javaagent.jar"
        volumeMounts:
        - name: otel-agent
          mountPath: /otel

      volumes:
      - name: otel-agent
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-nodeport
  namespace: app
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 8080          # 클러스터 내부 포트
      targetPort: 8080    # Pod 내부 Tomcat 포트
      nodePort: 30380     # 외부 접근용 포트

