---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-svc
  namespace: app
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 8080          # 클러스터 내부 접근 포트
      targetPort: 8080    # Pod 내부 Tomcat 포트
      nodePort: 30380     # 외부 접근용 포트 (30000~32767 범위)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat
        image: tomcat:10-jdk17
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.new-lgtm.svc.cluster.local:12345"
        - name: OTEL_SERVICE_NAME
          value: "tomcat-app"
        volumeMounts:
        - name: otel-agent
          mountPath: /otel
        command: ["catalina.sh", "run"]
        args: []
        # JVM 옵션에 javaagent 추가
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/otel/opentelemetry-javaagent.jar"
      volumes:
      - name: otel-agent
        configMap:
          name: otel-java-agent
