mode: deployment

image:
  repository: otel/opentelemetry-collector
  tag: "0.98.0"
  pullPolicy: IfNotPresent

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    loki:
      endpoint: http://loki-write.new-lgtm.svc.cluster.local:3100/loki/api/v1/push
      labels:
        resource:
          k8s.pod.name: "pod"
          k8s.namespace.name: "namespace"
          service.name: "service"
        attributes:
          severity_text: "level"

  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki]

