  loki:
  
    memberlist:
      joinMembers:
        - loki-memberlist
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true

    # storage_config:
    #   aws:
    #     region: eu-west-2
    #     bucketnames: loki-chunk
    #     s3forcepathstyle: false

    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        s3: null
        endpoint: http://new-minio.new-lgtm.svc.cluster.local:9000
        region: dummy
        secretAccessKey: HTfcF2waO5kCm7W7HxGaeD8MKOYba0Y4S5KBR2x9
        accessKeyId: tq5CBo9EEcld6752NwSd
        s3ForcePathStyle: true
        insecure: true


  deploymentMode: SimpleScalable

  backend:
    replicas: 2
  read:
    replicas: 2
  write:
    replicas: 2 # To ensure data durability with replication

  # Enable minio for storage
  # storage_config:
  #   aws:
  #     region: eu-west-2
  #     bucketnames: loki-chunk
  #     s3forcepathstyle: false
  # storage:
  #   bucketNames:
  #       chunks: loki-chunks
  #       ruler: loki-ruler
  #       admin: loki-admin
  #   type: s3
  #   s3:
  #     s3: null
  #     endpoint: http://minio.lgtm.svc.cluster.local:9000
  #     region: dummy
  #       #secretAccessKey: 6PGWlBj9eTROb1IoAsIaSHzRIHJU9SDaieAku9yD
  #       #accessKeyId: ZbhqfXcK79BoEbIfM9mz
  #     s3ForcePathStyle: true
  #     insecure: true
  minio:
    enabled: false

  gateway:
    service:
      type: LoadBalancer

  chunksCache:
    allocatedMemory: 1024
    #chunksCache:
    #  allocatedMemory: 1024

    #  l2:
    #    allocatedMemory: 1024
