deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  extraEnv:
    - name: GOMEMLIMIT
      value: 3750MiB

loki:
  auth_enabled: false
  config: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    ingester:
      chunk_encoding: snappy
      lifecycler:
        ring:
          kvstore:
            store: inmemory

    schema_config:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: http://minio.lgtm.svc.cluster.local:9000
        bucketnames: loki-chunks
        access_key_id: minioadmin
        secret_access_key: minioadmin
        insecure: true

    limits_config:
      allow_structured_metadata: true

    querier:
      max_concurrent: 2

minio:
  enabled: false
