persistence:
  enabled: true

service:
  type: NodePort
  nodePort: 31180

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the grafana-server to be run with an arbitrary user
  ##
  enabled: false
# grafana.ini:
#   server:
#     domain: "http://14.63.186.64:31180"