name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm charts
        run: |
          mkdir -p .deploy
          helm package charts/* --destination .deploy
          helm repo index .deploy --url https://kjhooni.github.io/helm-charts/
          cp index.md .deploy/
          cp _config.yml .deploy/

      - name: Publish to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .deploy
          nojekyll: false
